### ISSUE TITLE
"Authenticate with 42" button doesn't work

### ISSUE THREAD

**Issue by hcremers19** [FreekBes/improved_intra#52] opened 2023-03-17 16:14 UTC
**Describe the bug**
The changes made in the Improved Intra settings aren't applied to the Intra because it is impossible to authenticate with 42 from the extension menu 

**To Reproduce**
1. Go to the Intra
2. Click on the extensions menu in the top bar
3. Click on the Improved Intra extension
4. Click on "Authenticate with 42"
5. A window will open and close immediately
6. The process can be repeated indefinitely without the user being authenticated

**Expected behavior**
The user should be connected to their account and their chosen settings should be synced

**Screenshots**
<img width="213" alt="Extension_menu" src="https://user-images.githubusercontent.com/91729938/225958121-14099f32-307b-49cb-b81a-4f2e1645fc38.png">
<img width="923" alt="Intra_profile" src="https://user-images.githubusercontent.com/91729938/225958179-f0f054ed-a659-4d53-a441-3b3c003fdd1f.png">
<img width="700" alt="Improved_Intra_settings-location" src="https://user-images.githubusercontent.com/91729938/225958224-03384e64-649f-4d18-999a-221284323670.png">
<img width="700" alt="Improved_Intra_Settings-blackhole" src="https://user-images.githubusercontent.com/91729938/225958252-7ff25373-01d3-49e9-9fd8-ec65ad285f18.png">

**Desktop information (please complete the following information):**
Current server version: 3.0.2
Server target version: 4.0.0
Extension version: 4.0.3
Browser: Opera 96.0.0.0
OS: macOS 10.15.7

**Comment by FreekBes** [comment] 2023-03-17 16:24
Can you share with me the logs from the extension's background script, just after having clicked the button?

You'll have to open the Developer Tools on the background view for this. See https://dev.opera.com/extensions/testing/ for how to get there. If you have no experience in doing this and are unable to figure it out, I can also provide you with step-by-step instructions.

**Comment by FreekBes** [comment] 2023-03-19 16:58
I've just released a new version for both the extension and the back-end server ([v4.0.4](https://github.com/FreekBes/improved_intra/releases/tag/v4.0.4) and [Server v3.1.1](https://github.com/FreekBes/improved_intra_server/releases/tag/v3.1.1) respectively), hopefully fixing this issue. I was unable to reproduce it myself but found many other bugs in the session management system that are now fixed, and it is likely these bugs were causing this front-end issue as well.

If you do however still experience this bug even after updating the extension to 4.0.4, please re-open this issue.

**Closed by FreekBes** 2023-03-19 16:58 UTC
Labels: bug
